Fix bug
When there are multiple project dependencies, not assign a more
accurate version number for android.support lib will cause error like:

* What went wrong:
Execution failed for task ':react-native-getui:processReleaseResources'.
> com.android.ide.common.process.ProcessException: Failed to execute
aapt